version: '3'

services:
  # CUSTOM SERVICES
  web_server:
    build: './docker_web_server'
    ports:
      - 9001:80
    environment: 
      - VIRTUAL_HOST=web.localhost:8080
  api_server:
    build: './docker_api_server'
    ports:
      - 9002:80
    environment: 
      - VIRTUAL_HOST=api.localhost:8080

  # NGINX REVERSE PROXY
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
 
